package org.history;

import org.flywaydb.core.api.callback.Callback;
import org.flywaydb.core.api.callback.Context;
import org.flywaydb.core.api.callback.Event;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Creates/inserts into a table of database migration history (called FlywayMigrations) using the same connection as the migration.
 */
public class DatabaseMigrationHistory implements Callback {

    @Override
    public boolean supports(Event event, Context context) {
        return event == Event.AFTER_EACH_MIGRATE;
    }

    @Override
    public boolean canHandleInTransaction(Event event, Context context) {
        return true;
    }

    @Override
    public void handle(Event event, Context context) {
        try (Statement statement =  context.getConnection().createStatement()){
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS FlywayMigrations(
                    MigrationID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Description VARCHAR(200),
                    Type VARCHAR(50),
                    ApproximateTime DATETIME
                    );""");
            PreparedStatement insertStatement = context.getConnection().prepareStatement("INSERT INTO FlywayMigrations (Description, Type, ApproximateTime) " +
                    "VALUES ((?)" + ",(?) " + ", CURRENT_TIMESTAMP());");
            insertStatement.setString(1, context.getMigrationInfo().getDescription());
            insertStatement.setString(2, context.getMigrationInfo().getType().name());
            insertStatement.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public String getCallbackName() {
        return "DatabaseMigrationHistory";
    }
}
