package org.history;

import org.flywaydb.core.api.callback.Callback;
import org.flywaydb.core.api.callback.Context;
import org.flywaydb.core.api.callback.Event;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;

/**
 * Creates/inserts into a table of database migration history (called FlywayMigrations) using the same connection as the migration.
 */
public class DatabaseMigrationHistory implements Callback {
    private static SimpleDateFormat format = new SimpleDateFormat("");

    @Override
    public boolean supports(Event event, Context context) {
        return event == Event.AFTER_EACH_MIGRATE;
    }

    @Override
    public boolean canHandleInTransaction(Event event, Context context) {
        return true;
    }

    @Override
    public void handle(Event event, Context context) {
        LocalDateTime now = LocalDateTime.now();
        try (Statement statement =  context.getConnection().createStatement()){
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS FlywayMigrations(
                    MigrationID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Description VARCHAR(200),
                    Type VARCHAR(50),
                    ApproximateTime DATETIME
                    );""");
            PreparedStatement insertStatement = context.getConnection().prepareStatement("INSERT INTO FlywayMigrations (Description, Type, ApproximateTime) " +
                    "VALUES (" + context.getMigrationInfo().getDescription() + ", " + context.getMigrationInfo().getType().name() + ", " + "(?));");
                    insertStatement.setObject(1, now);
                    insertStatement.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public String getCallbackName() {
        return "DatabaseMigrationHistory";
    }
}
