package org.history;

import org.flywaydb.core.api.callback.Callback;
import org.flywaydb.core.api.callback.Context;
import org.flywaydb.core.api.callback.Event;
import org.flywaydb.core.extensibility.MigrationType;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;

public class DatabaseMigrationHistory implements Callback {
    @Override
    public boolean supports(Event event, Context context) {
        return event == Event.AFTER_EACH_MIGRATE;
    }

    @Override
    public boolean canHandleInTransaction(Event event, Context context) {
        return false;
    }

    @Override
    public void handle(Event event, Context context) {
        try (Statement statement =  context.getConnection().createStatement()){
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS FlywayMigrations(
                    MigrationID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    Description VARCHAR(200),
                    Type VARCHAR(50),
                    ApproximateTime DATE
                    );""");
            statement.execute("INSERT INTO FlywayMigrations (Description, Type, ApproximateTime) " +
                    "VALUES (" + context.getMigrationInfo().getDescription() + ", " + context.getMigrationInfo().getType().name() + ", " + (new Date()) + ");");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public String getCallbackName() {
        return "";
    }
}
