package org.history;

import org.flywaydb.core.api.callback.Callback;
import org.flywaydb.core.api.callback.Context;
import org.flywaydb.core.api.callback.Event;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;

/**
 * Creates/inserts into a table of database migration error history (called FlywayMigrationErrors) using the same connection as the migration.
 */
public class ErrorHistory implements Callback {

    @Override
    public boolean supports(Event event, Context context) {
        return event == Event.AFTER_EACH_MIGRATE_ERROR;
    }

    @Override
    public boolean canHandleInTransaction(Event event, Context context) {
        return true;
    }

    @Override
    public void handle(Event event, Context context) {
        try (Statement statement =  context.getConnection().createStatement()){
            statement.execute("CREATE TABLE IF NOT EXISTS FlywayMigrationErrors(" +
                            "MigrationID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "Environment VARCHAR(200)," +
                    "Username VARCHAR(50), " +
                    "ApproximateTime DATETIME);");
            PreparedStatement insertStatement = context.getConnection().prepareStatement("INSERT INTO FlywayMigrationErrors (Environment, Username, ApproximateTime) " +
                    "VALUES ((?)" + ",(?) " + ", CURRENT_TIMESTAMP());");
            insertStatement.setString(1, context.getConfiguration().getCurrentEnvironmentName());
            insertStatement.setString(2,context.getConfiguration().getUser());
            insertStatement.executeUpdate();
            ResultSet results = statement.executeQuery("SELECT * FROM FlywayMigrationErrors");
            context.getConnection().commit();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public String getCallbackName() {
        return "MigrationErrorHistory";
    }
}
