package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Statement;

public class V1__CreateCustomersTable extends BaseJavaMigration {
    @Override
    public void migrate(Context context) throws Exception {
        try (Statement statement = context.getConnection().createStatement()) {
             statement.execute("CREATE TABLE customers(" +
                    "CustomerID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "FirstName VARCHAR(25)," +
                    "LastName VARCHAR(25)," +
                     "Email VARCHAR(254)" +
                     ");");
            statement.execute("INSERT INTO customers (FirstName, LastName, Email)" +
                    "VALUES" +
                    "('Ariel', 'Cann', 'Golos1@gmail.com')," +
                    "('Ariel', 'Cann', 'Golos1@gmail.com')," +
                    "('Ariel', 'Cann', 'Golos1@gmail.com')," +
                    "('Ariel', 'Cann', 'Golos1@gmail.com')," +
                    "('Ariel', 'Cann', 'Golos1@gmail.com');");
        }
    }
}
