name: test_and_publish
on:
  push:
    branches:
      - 'master'
jobs:
  test_and_publish:
    permissions:
      id-token: write
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: 'maven'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: 'us-east-2'
          role-to-assume: ${{secrets.AWS_ROLE}}
      - run: mvn --batch-mode verify
      - name: Publish package
      - run: mvn deploy -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}